### PR TITLE
Replace ScrollView by FlatList for performance

### PR DESCRIPTION
**Pull request by AntonioVdlC**
First of all, thanks for this component, it's great stuff!

I am using it in an app where I am building a 300+ item chooser (yeah, I know, I may actually need to rethink that UX-wise 😅) and so I had some performance issues that seem to be due to the fact that you are using a `ScrollView` inside `OptionList`.

Replacing the `ScrollView` with a `FlatList` component did the trick though (at least for me), so I'm just opening this PR here in case that is of any use for you. Please feel free to just delete this PR if it isn't!

All the best for the v2! 🙂

### CODE REVIEW

**Comment by gs-akhan** [comment]
Amazing !!! Thank you for this. I will review this and get back to you. 
Most probably It would be amazing to have this merged. 

Thanks

**Comment by gs-akhan** [comment]
Hi, I was wondering this would fail for uses who are on RN 0.40 .. Am I right ?

**Comment by AntonioVdlC** [comment]
Good catch! It seems like it was introduced fairly recently (v0.43 from my quick Google search).

A better idea would be to implement it in the v2 then if you still want to give support for older versions of React Native!

Please feel free to delete this PR then! 🙂

**Comment by st0ffern** [comment]
i will fix it in the v2 😉

**Pull request closed without merging**
