### PR TITLE
Allow options to take in object and string

### PR DESCRIPTION
**Pull request by KeerthiHarish**
Currently options allow only string type as it children. I want to show some icons with text in each options as below:
```
<Option value = "General">
  <View>
    <Icon name='user' size={25} color={'#555555'} style={{padding: 5}} /> General
  </View>
</Option>
```

### CODE REVIEW

**Comment by gs-akhan** [comment]
Hi,
Are you sure this works ?

**Comment by gs-akhan** [comment]
HI,
Any update on this ?

**Comment by KeerthiHarish** [comment]
@gs-akhan Sorry for late reply. I tested this locally and it worked.

**Comment by st0ffern** [comment]
@gs-akhan why dont you test it yourself?

**Comment by gs-akhan** [comment]
I did. It failed . You cannot pass view to a text component ..

**Comment by st0ffern** [comment]
@KeerthiHarish checkout and fix the issue  😉

**Comment by KeerthiHarish** [comment]
@stoffern Sure. Will fix it. @gs-akhan Any error message or reason for failure?

**Pull request closed without merging**
